name: Btrust Builders Learn Bitcoin CLI Chapter 3 Exercises

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  test-bitcoin-cli-exercises:
    runs-on: ubuntu-latest # Use the latest Ubuntu environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Check out the repository code

      - name: Run Bitcoin Core setup script
        run: |
          chmod +x .github/setup.sh
          .github/setup.sh

      - name: Start bitcoind in regtest mode
        run: |
          bitcoind -regtest -daemon
          echo "Waiting for bitcoind to be ready..."

          # Wait for bitcoind to start (max 30s)
          for i in {1..30}; do
            if bitcoin-cli -regtest getblockchaininfo > /dev/null 2>&1; then
              echo "bitcoind is ready!"
              break
            fi
            echo "Still waiting for bitcoind..."
            sleep 1
          done

      - name: Verify Wallet Creation
        run: |
          chmod +x submission/01.sh
          WALLET=$(submission/01.sh)
          if [[ "$WALLET" == *"btrustwallet"* ]]; then
            echo "Wallet creation passed!"
          else
            echo "Wallet creation failed!"
            exit 1
          fi

      - name: Verify Wallet Balance Check
        run: |
          chmod +x submission/02.sh
          BALANCE=$(submission/02.sh)
          if [[ "$BALANCE" == "0.00000000" ]]; then
            echo "Wallet balance check passed!"
          else
            echo "Wallet balance check failed!"
            exit 1
          fi

      - name: Verify Legacy Address Generation
        run: |
          chmod +x submission/03.sh
          LEGACY_ADDRESS=$(submission/03.sh)
          echo "LEGACY_ADDRESS=$LEGACY_ADDRESS" >> $GITHUB_ENV
          if [[ "$LEGACY_ADDRESS" =~ ^[mn][a-km-zA-HJ-NP-Z1-9]{25,34}$ ]]; then
            echo "Legacy address generation passed!"
          else
            echo "Legacy address generation failed!"
            exit 1
          fi

      - name: Verify P2SH Address Generation
        run: |
          chmod +x submission/04.sh
          P2SH_ADDRESS=$(submission/04.sh)
          echo "P2SH_ADDRESS=$P2SH_ADDRESS" >> $GITHUB_ENV
          if [[ "$P2SH_ADDRESS" =~ ^2[0-9a-zA-Z]{25,34}$ ]]; then
            echo "P2SH address generation passed!"
          else
            echo "P2SH address generation failed!"
            exit 1
          fi

      - name: Verify Native SegWit Address Generation
        run: |
          chmod +x submission/05.sh
          NATIVE_SEGWIT_ADDRESS=$(submission/05.sh)
          echo "NATIVE_SEGWIT_ADDRESS=$NATIVE_SEGWIT_ADDRESS" >> $GITHUB_ENV
          if [[ "$NATIVE_SEGWIT_ADDRESS" =~ ^bcrt1[ac-hj-np-z02-9]{8,87}$ ]]; then
            echo "Native SegWit address generation passed!"
          else
            echo "Native SegWit address generation failed!"
            exit 1
          fi

      - name: Verify Taproot Address Generation
        run: |
          chmod +x submission/06.sh
          TAPROOT_ADDRESS=$(submission/06.sh)
          echo "TAPROOT_ADDRESS=$TAPROOT_ADDRESS" >> $GITHUB_ENV
          if [[ "$TAPROOT_ADDRESS" =~ ^bcrt1p[ac-hj-np-z02-9]{8,87}$ ]]; then
            echo "Taproot address generation passed!"
          else
            echo "Taproot address generation failed!"
            exit 1
          fi

      - name: Verify Address Validation
        run: |
          chmod +x submission/07.sh
          VALID=$(submission/07.sh)
          if [[ "$VALID" == "false" ]]; then
            echo "Address validation passed!"
          else
            echo "Address validation failed!"
            exit 1
          fi

      - name: Verify Message Signature
        run: |
          chmod +x submission/08.sh
          VALID=$(submission/08.sh)
          if [[ "$VALID" == "true" ]]; then
            echo "Message verification passed!"
          else
            echo "Message verification failed!"
            exit 1
          fi

      - name: Verify Taproot Address Using Descriptors
        run: |
          chmod +x submission/09.sh
          ACTUAL_OUTPUT=$(submission/09.sh)
          EXPECTED_OUTPUT="bcrt1puuky37nw03r8mzgnmhtvxg2cxxmzvdm5rvn362mtus3rayw6m2zqg5wwca"
          if [[ "$ACTUAL_OUTPUT" == "$EXPECTED_OUTPUT" ]]; then
            echo "Taproot address verification passed!"
          else
            echo "Taproot address verification failed!"
            exit 1
          fi
          
      - name: Run Capstone Exercise
        run: |
          chmod +x submission/10.sh
          
          # Install bc for floating point calculations
          sudo apt-get update && sudo apt-get install -y bc
          
          echo "Running the Bitcoin treasure hunt capstone exercise..."
          if submission/10.sh > treasure_hunt_output.log 2>&1; then
            echo "Capstone exercise completed successfully!"
            # Print the last 10 lines to see the summary
            echo "--- Treasure Hunt Summary ---"
            tail -n 10 treasure_hunt_output.log
            echo "---------------------------"
          else
            echo "Capstone exercise failed with exit code $?"
            cat treasure_hunt_output.log
            exit 1
          fi

